title: Moonshine IDE
host: 127.0.0.1
port: 4000

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed


exclude:
  - .idea/
  - .gitignore
  - vendor
  - _build.sh
  - _serve.sh

# Google Analytics
google_analytics: G-PX9YVENNVH